### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by frank-dspeed**
-DEPRECATED creatorrr/web-streams-polyfill replaced with new successor
-DEPRECATED RAWGIT as it is going to sun set phase.

### CODE REVIEW

**Comment by jimmywarting** [comment]
Thanks, I wonder doe if we could just remove the stream polyfill... writableStream are implemented now in the browser that also support readableStream

**Comment by frank-dspeed** [comment]
i see no reason to remove that documentation there are still a lot of windows xp users around the world with IE8 :)

**Comment by jimmywarting** [comment]
Windows XP and IE8-10 looks pretty dead to me.

**Comment by frank-dspeed** [comment]
@jimmywarting lol sure but not for the people :)

**Pull request merged**
